### ISSUE TITLE
The example doesn't cover the PDF

### ISSUE THREAD

**Issue by oSethoum** [html2any/layout#1]
Please add pdf example

**Comment by html2any** [comment]
Thank you for your feedback. The examples have been updated.
Certainly! You can add a header HTML and a footer HTML to ensure that every page has a header and footer. Here's an example:
`
        body := layout.NewBlock(&cssMap)
	if err := parser.ParseHTML(htmls["body"], body); err != nil {
		return nil, err
	}
        if _, pages, err := layout.CacuPages(body, layout.A4_Width, "NotoSansSC", NewLayout(sfnt)); err != nil {
		return nil, err
	} else {
		for _, tpl := range receipt {
			header := layout.NewBlock((&cssMap))
			if err := parser.ParseHTML(htmls["header"], header); err != nil {
				return nil, err
			}
			header.GetBlockByID("TT").SetContent("Receipt（" + tpl + "）")

			if _, err := layout.CacuHeight(header, layout.A4_Width, "NotoSansSC", NewLayout(sfnt)); err != nil {
				return nil, err
			}

			tt := "TotalPage:" + strconv.Itoa(len(pages))

			for i, page := range pages {
				footer := layout.NewBlock((&cssMap))
				if err := parser.ParseHTML(htmls["footer"], footer); err != nil {
					return nil, err
				}
				footer.GetBlockByID("tail").SetContent(tpl + ",Page:" + strconv.Itoa(i+1) + "/" + tt)
				if _, err := layout.CacuHeight(footer, layout.A4_Width, "NotoSansSC", NewLayout(sfnt)); err != nil {
					return nil, err
				}
				render.pdf.AddPage()
				layout.RenderTo(header, render, 0, 0)
				layout.RenderTo(page, render, 0, 0)
				layout.RenderTo(footer, render, 0, 0)
			}
		}`

**Comment by html2any** [comment]
Thank you for your feedback. The examples have been updated.
Certainly! You can add a header HTML and a footer HTML to ensure that every page has a header and footer. Here's an example:
`

    body := layout.NewBlock(&cssMap)
	if err := parser.ParseHTML(htmls["body"], body); err != nil {
		return nil, err
	}
        if _, pages, err := layout.CacuPages(body, layout.A4_Width, "NotoSansSC", NewLayout(sfnt)); err != nil {
		return nil, err
	} else {
		for _, tpl := range receipt {
			header := layout.NewBlock((&cssMap))
			if err := parser.ParseHTML(htmls["header"], header); err != nil {
				return nil, err
			}
			header.GetBlockByID("TT").SetContent("Receipt（" + tpl + "）")
			if _, err := layout.CacuHeight(header, layout.A4_Width, "NotoSansSC", NewLayout(sfnt)); err != nil {
				return nil, err
			}
			tt := "TotalPage:" + strconv.Itoa(len(pages))
			for i, page := range pages {
				footer := layout.NewBlock((&cssMap))
				if err := parser.ParseHTML(htmls["footer"], footer); err != nil {
					return nil, err
				}
				footer.GetBlockByID("tail").SetContent(tpl + ",Page:" + strconv.Itoa(i+1) + "/" + tt)
				if _, err := layout.CacuHeight(footer, layout.A4_Width, "NotoSansSC", NewLayout(sfnt)); err != nil {
					return nil, err
				}
				render.pdf.AddPage()
				layout.RenderTo(header, render, 0, 0)
				layout.RenderTo(page, render, 0, 0)
				layout.RenderTo(footer, render, 0, 0)
			}
		}`

**Comment by oSethoum** [comment]
@html2any Thank you so much
