### ISSUE TITLE
Issue reading generated images

### ISSUE THREAD

**Issue by stefpap** [html2any/layout#2]
Hey there,
This is a very useful tool, thank you.

To the point, Im having an issue, after having generated an image as shown from the example.
When I try to 

```go
img, err := os.ReadFile("./out.png")
if err != nil {
	log.Fatal("reading image: %v", err)
}
decodedImg, _, err := image.Decode(bytes.NewBuffer(img))
if err != nil {
	log.Fatal("decoding image: %v", err)
}
```

I'm getting a `decoding image: unexpected EOF`. I also tried reading it with `github.com/disintegration/imaging` and it fails.
Which is weird because if I double click the image I can view using windows default photo viewer.

Ongoing discussion seems to think the image might be prematurely closed https://github.com/golang/go/issues/45902

**Comment by html2any** [comment]
You may take a look at this library [go-libjpeg](https://github.com/pixiv/go-libjpeg), which is faster than image/jpeg. In my tests, some non-standard images were compatible
